branches:
  only:
  - master
language: python
python:
- '3.4'
before_script:
- if [ -n "${GH_TOKEN}" ] && [ "${TRAVIS_BRANCH}" == "master" ] && [ "${TRAVIS_PULL_REQUEST}"
  == "false" ]; then pip install pygithub; pip install pygithub3; fi
script:
- if [ -n "${GH_TOKEN}" ] && [ "${TRAVIS_BRANCH}" == "master" ] && [ "${TRAVIS_PULL_REQUEST}"
  == "false" ]; then python3 tools/deploy.py; fi
- python3 tools/sqf_wrapper_validation.py
notifications:
  email:
    on_success: never
    on_failure: change
  slack:
    on_success: change
    on_failure: always
    on_start: never
    secure: EqEjlYaUPJnyq68WSgKHEQ8HGto4hu+2amivPDE/5b9fEbugz0dtHC2bNoCvAFX+5sQJ6qqSWyVAcZ5KqNCW8fRs5BqS1lODSHygprlo6vyShjl36KBjvwLABVsyTUosmwNNyhW+XKy4O951KW8zix2N2amg1PaTko3YgZVIPLaPCgnzawj/2mPP+0tNT4Mz1qpJ3/JEwXcZ7zCu+ONbFifjjmpnwfGHCSs8cEDGFONiokAOnV7/M+PSwkYdMGxVLhr3HxrvlEFCUO+p+7CyHDL0M+isJrrloqMUTAgqaV/RVVtk19tQ6zno5iSTTrpycLZ7YkHuhC5fuTGozWUSQwSdE9YtC4xugygdjkx6Hxqwdw9pAjtx2ZnDoraNq285qk8ONIJGS8ZAYX1tbTXjVlFSvoxRE56t0+yS+8DVP41QY9WXmzT7hdqBno2fFLzgATx+EqIms6DUVw1a9B2jYZYj/hqlNmTOZcGjFCx5en+FgBzMBokRnIPFfhe1g0WgTeg2q3K3SuCFMOzRli8ZZNYAkSA5/slx0Nw0k7wQT0iYVnZqRcZdn+PxVqR4d4RWDlYyxQyKZUJPMQykfweqJTt7LyNYjmQOXtzcg5QCOlbyKAozknzaLAvvzkQ3xCcsD5pKFn/ZRS8w9E8nR8b3mmUY7u2ysEq8RloCOi0bUSo=
env:
  global:
    secure: agYEwpL95+e0vVIJ6H/UXJwiY0ubCFoNM7SoGFikr+ZV609OeL7KPS7gG7TV57HUP7lPv05JIntFAn37NZjKptZYJTBnmTPT7mmS/fn3LfuFwldvD2m+PUclz5cO2WMM+utWi+JnvpYPficdlLoHOlW9NjigsgFT/Xd49MkDyxpxCZ2C3KiSzOy4EAV+UNMDiq5+iUKNNMfTINYz2ZTF4muBQb4oGzpriS/4sEUKt1mOjZNGf2tX+JpppjDCnic9Wo3BTixIhgB/Ja0LvYuAoaERSFPioxj50J4oQemyfuGdabCM3D2Xo0i4OpNsM+Au9iXQaL9bQRvTfVSSN1T6KARmuw134MjuPq9G4ppRIEHeKzirqUpMNw+ja/No7I5111Cq0fwm/Y+ZqaxPf1YRnt5jLweggngKrb9672IkrW7M10pvleUXV5RWYBXkfwWxyNatU7dt231gS7n1jTOOvGDltvyHjnZSuCR82IevE4waCxtfGAfgwqYj14vVyQoxLIbFcFpJJ3ANRdwpHYaIlcJ03GSG5luRQ/5prwIEmweS1XlGM400XVjWpW34pHIUdjzuFyiDuSWrEWukjv57XCk7etpDTfp2rtV5tghXwqfa76SpjsIT1ooJgjL/3nrNrR3sFKWDcaC6okeB1nBZ/Fdg1GpXztf54dcyQdikqNY=
