name: CI

on: [push, pull_request]

jobs:
  mod:
    runs-on: ubuntu-20.04
    steps:
      - name: git checkout
        uses: actions/checkout@v2

      - name: HEMTT build
        uses: docker://hemtt/hemtt:0.7.6
        with:
          entrypoint: hemtt
          args: build --release

      - name: Upload mod
        uses: actions/upload-artifact@v1
        with:
          name: 'mod'
          path: releases/1.0.0/@intercept

  extension-linux:
    runs-on: ubuntu-20.04
    steps:
      - name: git checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install -y g++-8-multilib

      - name: Build Linux 64 bit
        run: mkdir build-linux64 && cd build-linux64 && cmake -DCMAKE_TOOLCHAIN_FILE=../linux64/toolchain.cmake -DCMAKE_BUILD_TYPE=Release .. && make
        env:
          CC: gcc-8
          CXX: g++-8

      - name: Upload Linux 64 bit
        uses: actions/upload-artifact@v1
        with:
          name: intercept_x64.so
          path: build-linux64/src/host/intercept_dll/intercept_x64.so

  extension-windows:
    runs-on: windows-2019
    steps:
      - name: git checkout
        uses: actions/checkout@v2

      - name: Build Windows 32 bit
        run: mkdir build-win32 && cd build-win32 && cmake -DCMAKE_BUILD_TYPE=Release -G "Visual Studio 16 2019" -A Win32 .. && cmake --build . --config Release

      - name: Build Windows 64 bit
        run: mkdir build-win64 && cd build-win64 && cmake -DCMAKE_BUILD_TYPE=Release -G "Visual Studio 16 2019" -A x64 .. && cmake --build . --config Release

      - name: Upload Windows 32 bit
        uses: actions/upload-artifact@v1
        with:
          name: intercept.dll
          path: build/win32/intercept/Release/intercept.dll

      - name: Upload Windows 64 bit
        uses: actions/upload-artifact@v1
        with:
          name: intercept_x64.dll
          path: build/win64/intercept/Release/intercept_x64.dll

  package:
    runs-on: ubuntu-20.04
    needs:
      - extension-linux
      - extension-windows
      - mod
    steps:
      - name: Download mod
        uses: actions/download-artifact@v1
        with:
          name: 'mod'
          path: '@intercept'

      - name: Download Linux 64 bit
        uses: actions/download-artifact@v1
        with:
          name: intercept_x64.so
          path: '@intercept'

      - name: Download Windows 32 bit
        uses: actions/download-artifact@v1
        with:
          name: intercept.dll
          path: '@intercept'

      - name: Download Windows 64 bit
        uses: actions/download-artifact@v1
        with:
          name: intercept_x64.dll
          path: '@intercept'

      - name: Upload built mod
        uses: actions/upload-artifact@1.0.0
        with:
          name: '@intercept'
          path: '.'
